spring:
  application:
    name: employees-db

  r2dbc:
    username: app
    password: 1234
    url: r2dbc:postgresql://localhost:8082/employees-db
  flyway:
    url: jdbc:postgresql://localhost:8082/employees-db
    locations: classpath:db/postgres/migration
  main:
    allow-bean-definition-overriding: true
# R2DBC URL
r2dbc:
  url: r2dbc:h2:mem://./employees-db

