spring:
  application:
    name: employees-app

  r2dbc:
    username: app
    password: 1234
    url: r2dbc:postgresql://localhost:5432/employees
  flyway:
    url: jdbc:postgresql://localhost:5432/employees
    locations: classpath:db/postgres/migration
  main:
    allow-bean-definition-overriding: true
# R2DBC URL
r2dbc:
  url: r2dbc:h2:mem://./employees

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters